### ISSUE TITLE
The snap application crashes

### ISSUE THREAD

**Issue by CalvoM** [itsmejoeeey/eversticky#5] opened 2022-05-11 08:23 UTC
I am using an Ubuntu jammy machine and I installed eversticky using the snap, and it crashes all time.
Here is the crash log 
```sh
tk-Message: 11:17:41.874: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:17:41.875: Failed to load module "canberra-gtk-module"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Qt: Session management error: Could not open network socket
[2022-05-11T11:17:41] propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.177\" (uid=1000 pid=132789 comm=\"/snap/eversticky/1/usr/bin/eversticky \" label=\"snap.eversticky.eversticky (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1471 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
[2022-05-11T11:17:41] nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.177\" (uid=1000 pid=132789 comm=\"/snap/eversticky/1/usr/bin/eversticky \" label=\"snap.eversticky.eversticky (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1471 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
[2022-05-11T11:17:41] "Object path cannot be empty"
[2022-05-11T11:17:46] Sandboxing disabled by user.
[2022-05-11T11:17:46] WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
[2022-05-11T11:17:47] Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
[132968:132968:0100/000000.083067:ERROR:broker_posix.cc(43)] Invalid node channel message
[1]    132789 IOT instruction (core dumped)  eversticky
```

However, the .deb file works correctly.

**Comment by itsmejoeeey** [comment] 2022-05-16 07:28
I've encountered this issue myself on Ubuntu 20.04.

Unfortunately there is no fix for this issue at the moment.

[This is the bug report for snapd.](https://bugs.launchpad.net/snapd/+bug/1866855) It is caused by some incompatibility between NVIDIA and snap when an application uses OpenGL contexts (in our case the Chromium QWebEngineView).

> [It’s unfortunate that this bug doesn’t look like it’ll be fixed any time soon, it must effect a lot of people if it’s everyone who uses Debian/Nvidia card.](https://forum.snapcraft.io/t/install-applications-without-snap/22673/12)

**Comment by itsmejoeeey** [comment] 2022-06-04 03:53
I've managed to [force the snap version of the app to use software rendering](https://stackoverflow.com/a/69755589/3213602). This, although an imperfect fix, solves the issue.

**Closed as completed by itsmejoeeey** 2022-06-04 03:53 UTC
Labels: bug, upstream
